# maven BuildSpec

version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - yum update -y
      - npm install -g npm@8.19.4
      - npm install -g typescript
      - npm i react react-dom react-router-dom


  build:
    commands:
      - echo Entered the build phase...
      - echo Building the project...
      - npm run build
      - echo Finished the build phase.
  post_build:
    commands:
      - aws s3 cp --recursive dist s3://$BUCKET_NAME